import type { NextPage, NextPageContext } from 'next';
import { useSession, signIn, signOut, getSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import { clearUser, setUser } from '../store/app/user.slice';
import { useAppDispatch, useAppSelector } from '../store/hook';
import styles from '../styles/Home.module.css';

const Home: NextPage<any> = () => {
    const dispatch = useAppDispatch();
    const user = useAppSelector(state => state.app.user);

    const { data: session } = useSession();

    useEffect(() => {
        if (session) {
            const { user: sessionUser } = session;
            if (sessionUser?.email && !user.email) {
                dispatch(setUser({ email: sessionUser.email }));
            }
        }
    }, [session, dispatch, user]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome {!!session ? user.email : 'Guest'}!
                </h1>
                {!session ? (
                    <button
                        onClick={async () => {
                            const response = await signIn('credentials', {
                                redirect: false,
                                email: 'admin@mail.com',
                                password: 'adminpwd',
                            });
                            console.log('login response', response);
                        }}
                    >
                        Login
                    </button>
                ) : (
                    <button
                        onClick={async () => {
                            await signOut({
                                redirect: false,
                            });
                            dispatch(clearUser());
                        }}
                    >
                        Logout
                    </button>
                )}

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
